# Generated by Django 2.2 on 2020-04-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200415_0044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
